---
<<<<<<< HEAD
=======
- name: create my.cnf
  template: src=templates/my.cnf.j2 dest=/etc/my.cnf

- name: create /var/lib/mysql/data
  file: path={{ item }} state=directory
  with_items:
  - /var/lib/mysql/data



>>>>>>> e073ae8988610414a2798c9ec197ab7abe880c67
- name: check if ndbd is running already
  shell: ps aux | grep ndbd | grep -v grep
  ignore_errors: yes
  changed_when: false
  register: ndbd_status


- name: start ndbd
  command: /usr/local/bin/ndbd 
  async: 45
  poll: 0
  when: ndbd_status.rc != 0
