apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-wipe-dir-{{ randAlphaNum 5 | lower }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "30"
  labels:
    name: wipe-data
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-wipe-data
      labels:
        name: wipe-data
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      restartPolicy: Never
      containers:
      - name: wipe-data
        image: busybox:latest
        command: [ "/bin/sh", "-c" ]
        args: ["ls -l /var/lib/mysql; rm -rf /var/lib/mysql/*; ls -l /var/lib/mysql"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: {{ .Chart.Name }}-mysql
      volumes:
        - name: {{ .Chart.Name }}-mysql
{{- if .Values.existingPVCName }}
          persistentVolumeClaim:
            claimName: {{ .Values.existingPVCName }}
{{ else }}
          hostPath:
            path: /var/lib/mysql-{{ .Release.Name }}
{{ end }}
